debian/tmp/usr/lib/iceweasel/.autoreg usr/lib/iceweasel
debian/tmp/usr/lib/iceweasel/components usr/lib/iceweasel
debian/tmp/usr/lib/iceweasel/browserconfig.properties usr/share/iceweasel
debian/iceweasel-xremote-client usr/lib/iceweasel

debian/tmp/usr/lib/iceweasel/defaults/preferences usr/share/iceweasel/defaults
debian/tmp/usr/lib/iceweasel/searchplugins usr/share/iceweasel
debian/tmp/usr/lib/iceweasel/icons usr/share/iceweasel
debian/tmp/usr/lib/iceweasel/chrome usr/share/iceweasel
debian/tmp/usr/lib/iceweasel/modules usr/share/iceweasel

debian/tmp/usr/lib/iceweasel/application.ini usr/lib/iceweasel

debian/tmp/usr/lib/iceweasel/defaults/profile etc/iceweasel/

debian/iceweasel.desktop usr/share/applications
debian/iceweaselrc etc/iceweasel

build-iceweasel/debian/branding/mozicon16.xpm usr/share/iceweasel/icons/
build-iceweasel/debian/branding/mozicon50.xpm usr/share/iceweasel/icons/
build-iceweasel/debian/branding/mozicon128.png usr/share/iceweasel/icons/
build-iceweasel/debian/branding/document.png usr/share/iceweasel/icons/

debian/iceweasel.js etc/iceweasel/pref

debian/debsearch.xml usr/share/iceweasel/searchplugins

debian/tmp/usr/lib/iceweasel/extensions/\{972ce4c6-7e08-4474-a285-3208198ce6fd\} usr/lib/iceweasel/extensions

build-iceweasel/debian/branding/iceweasel.xpm usr/share/pixmaps

debian/firefox usr/bin

debian/branding/aboutIce.js usr/lib/iceweasel/components
build-iceweasel/dist/bin/chrome/ice.* usr/share/iceweasel/chrome
