usr/lib/libxul.so.*
usr/lib/libxpcom.so.*
usr/lib/libxpcomglue.so.*
usr/lib/libgtkembedmoz.so.*

usr/lib/xulrunner/libjavaxpcomglue.so

usr/lib/xulrunner/components/libauth.so
usr/lib/xulrunner/components/libautoconfig.so
usr/lib/xulrunner/components/libcookie.so
usr/lib/xulrunner/components/libfileview.so
usr/lib/xulrunner/components/libmyspell.so
usr/lib/xulrunner/components/libpermissions.so
usr/lib/xulrunner/components/libpipboot.so
usr/lib/xulrunner/components/libpipnss.so
usr/lib/xulrunner/components/libpippki.so
usr/lib/xulrunner/components/libspellchecker.so
usr/lib/xulrunner/components/libsystem-pref.so
usr/lib/xulrunner/components/libtransformiix.so
usr/lib/xulrunner/components/libuniversalchardet.so
usr/lib/xulrunner/components/libwebsrvcs.so
usr/lib/xulrunner/components/libxmlextras.so
usr/lib/xulrunner/components/libxulutil.so
