etc/gre.d/libxul0d.conf

usr/lib/xulrunner/dependentlibs.list

usr/lib/xulrunner/javaxpcom.jar

usr/lib/xulrunner/greprefs usr/share/xulrunner
usr/lib/xulrunner/defaults/pref usr/share/xulrunner/defaults
usr/lib/xulrunner/defaults/autoconfig usr/share/xulrunner/defaults

usr/lib/xulrunner/res usr/share/xulrunner

usr/lib/xulrunner/chrome/classic* usr/share/xulrunner/chrome
usr/lib/xulrunner/chrome/en-US* usr/share/xulrunner/chrome
usr/lib/xulrunner/chrome/toolkit* usr/share/xulrunner/chrome
usr/lib/xulrunner/chrome/pippki* usr/share/xulrunner/chrome
usr/lib/xulrunner/chrome/comm* usr/share/xulrunner/chrome

usr/lib/xulrunner/components/FeedProcessor.js
usr/lib/xulrunner/components/nsDefaultCLH.js
usr/lib/xulrunner/components/nsDictionary.js
usr/lib/xulrunner/components/nsFilePicker.js
usr/lib/xulrunner/components/nsHelperAppDlg.js
usr/lib/xulrunner/components/nsInterfaceInfoToIDL.js
usr/lib/xulrunner/components/nsProgressDialog.js
usr/lib/xulrunner/components/nsProxyAutoConfig.js
usr/lib/xulrunner/components/nsResetPref.js
usr/lib/xulrunner/components/nsSidebar.js
usr/lib/xulrunner/components/nsURLFormatter.js
usr/lib/xulrunner/components/nsXmlRpcClient.js

usr/lib/xulrunner/components/accessibility-atk.xpt
usr/lib/xulrunner/components/accessibility.xpt
usr/lib/xulrunner/components/alerts.xpt
usr/lib/xulrunner/components/appshell.xpt
usr/lib/xulrunner/components/appstartup.xpt
usr/lib/xulrunner/components/autocomplete.xpt
usr/lib/xulrunner/components/autoconfig.xpt
usr/lib/xulrunner/components/caps.xpt
usr/lib/xulrunner/components/chardet.xpt
usr/lib/xulrunner/components/chrome.xpt
usr/lib/xulrunner/components/commandhandler.xpt
usr/lib/xulrunner/components/commandlines.xpt
usr/lib/xulrunner/components/composer.xpt
usr/lib/xulrunner/components/content_base.xpt
usr/lib/xulrunner/components/content_html.xpt
usr/lib/xulrunner/components/content_htmldoc.xpt
usr/lib/xulrunner/components/content_xmldoc.xpt
usr/lib/xulrunner/components/content_xslt.xpt
usr/lib/xulrunner/components/content_xtf.xpt
usr/lib/xulrunner/components/cookie.xpt
usr/lib/xulrunner/components/directory.xpt
usr/lib/xulrunner/components/docshell.xpt
usr/lib/xulrunner/components/dom.xpt
usr/lib/xulrunner/components/dom_base.xpt
usr/lib/xulrunner/components/dom_canvas.xpt
usr/lib/xulrunner/components/dom_core.xpt
usr/lib/xulrunner/components/dom_css.xpt
usr/lib/xulrunner/components/dom_events.xpt
usr/lib/xulrunner/components/dom_html.xpt
usr/lib/xulrunner/components/dom_loadsave.xpt
usr/lib/xulrunner/components/dom_range.xpt
usr/lib/xulrunner/components/dom_sidebar.xpt
usr/lib/xulrunner/components/dom_storage.xpt
usr/lib/xulrunner/components/dom_stylesheets.xpt
usr/lib/xulrunner/components/dom_svg.xpt
usr/lib/xulrunner/components/dom_traversal.xpt
usr/lib/xulrunner/components/dom_views.xpt
usr/lib/xulrunner/components/dom_xbl.xpt
usr/lib/xulrunner/components/dom_xpath.xpt
usr/lib/xulrunner/components/dom_xul.xpt
usr/lib/xulrunner/components/downloads.xpt
usr/lib/xulrunner/components/editor.xpt
usr/lib/xulrunner/components/embed_base.xpt
usr/lib/xulrunner/components/extensions.xpt
usr/lib/xulrunner/components/exthandler.xpt
usr/lib/xulrunner/components/fastfind.xpt
usr/lib/xulrunner/components/feeds.xpt
usr/lib/xulrunner/components/filepicker.xpt
usr/lib/xulrunner/components/find.xpt
usr/lib/xulrunner/components/gfx.xpt
usr/lib/xulrunner/components/gksvgrenderer.xpt
usr/lib/xulrunner/components/history.xpt
usr/lib/xulrunner/components/htmlparser.xpt
usr/lib/xulrunner/components/imgicon.xpt
usr/lib/xulrunner/components/imglib2.xpt
usr/lib/xulrunner/components/inspector.xpt
usr/lib/xulrunner/components/intl.xpt
usr/lib/xulrunner/components/jar.xpt
usr/lib/xulrunner/components/jsconsole.xpt
usr/lib/xulrunner/components/jsdservice.xpt
usr/lib/xulrunner/components/layout_base.xpt
usr/lib/xulrunner/components/layout_printing.xpt
usr/lib/xulrunner/components/layout_xul.xpt
usr/lib/xulrunner/components/layout_xul_tree.xpt
usr/lib/xulrunner/components/locale.xpt
usr/lib/xulrunner/components/lwbrk.xpt
usr/lib/xulrunner/components/mimetype.xpt
usr/lib/xulrunner/components/mozbrwsr.xpt
usr/lib/xulrunner/components/mozfind.xpt
usr/lib/xulrunner/components/necko.xpt
usr/lib/xulrunner/components/necko_about.xpt
usr/lib/xulrunner/components/necko_cache.xpt
usr/lib/xulrunner/components/necko_cookie.xpt
usr/lib/xulrunner/components/necko_data.xpt
usr/lib/xulrunner/components/necko_dns.xpt
usr/lib/xulrunner/components/necko_file.xpt
usr/lib/xulrunner/components/necko_ftp.xpt
usr/lib/xulrunner/components/necko_http.xpt
usr/lib/xulrunner/components/necko_res.xpt
usr/lib/xulrunner/components/necko_socket.xpt
usr/lib/xulrunner/components/necko_strconv.xpt
usr/lib/xulrunner/components/necko_viewsource.xpt
usr/lib/xulrunner/components/oji.xpt
usr/lib/xulrunner/components/passwordmgr.xpt
usr/lib/xulrunner/components/pipboot.xpt
usr/lib/xulrunner/components/pipnss.xpt
usr/lib/xulrunner/components/pippki.xpt
usr/lib/xulrunner/components/plugin.xpt
usr/lib/xulrunner/components/pref.xpt
usr/lib/xulrunner/components/prefetch.xpt
usr/lib/xulrunner/components/profile.xpt
usr/lib/xulrunner/components/progressDlg.xpt
usr/lib/xulrunner/components/proxyObjInst.xpt
usr/lib/xulrunner/components/rdf.xpt
usr/lib/xulrunner/components/satchel.xpt
usr/lib/xulrunner/components/saxparser.xpt
usr/lib/xulrunner/components/spellchecker.xpt
usr/lib/xulrunner/components/storage.xpt
usr/lib/xulrunner/components/shistory.xpt
usr/lib/xulrunner/components/sidebar.xpt
usr/lib/xulrunner/components/toolkitprofile.xpt
usr/lib/xulrunner/components/toolkitremote.xpt
usr/lib/xulrunner/components/txmgr.xpt
usr/lib/xulrunner/components/txtsvc.xpt
usr/lib/xulrunner/components/ucnative.xpt
usr/lib/xulrunner/components/uconv.xpt
usr/lib/xulrunner/components/unicharutil.xpt
usr/lib/xulrunner/components/update.xpt
usr/lib/xulrunner/components/uriloader.xpt
usr/lib/xulrunner/components/urlformatter.xpt
usr/lib/xulrunner/components/webBrowser_core.xpt
usr/lib/xulrunner/components/webbrowserpersist.xpt
usr/lib/xulrunner/components/webshell_idls.xpt
usr/lib/xulrunner/components/websrvcs.xpt
usr/lib/xulrunner/components/widget.xpt
usr/lib/xulrunner/components/windowds.xpt
usr/lib/xulrunner/components/windowwatcher.xpt
usr/lib/xulrunner/components/xml-rpc.xpt
usr/lib/xulrunner/components/xpcom_base.xpt
usr/lib/xulrunner/components/xpcom_components.xpt
usr/lib/xulrunner/components/xpcom_ds.xpt
usr/lib/xulrunner/components/xpcom_io.xpt
usr/lib/xulrunner/components/xpcom_obsolete.xpt
usr/lib/xulrunner/components/xpcom_threads.xpt
usr/lib/xulrunner/components/xpcom_xpti.xpt
usr/lib/xulrunner/components/xpconnect.xpt
usr/lib/xulrunner/components/xpinstall.xpt
usr/lib/xulrunner/components/xulapp.xpt
usr/lib/xulrunner/components/xulapp_setup.xpt
usr/lib/xulrunner/components/xuldoc.xpt
usr/lib/xulrunner/components/xulrunner.xpt
usr/lib/xulrunner/components/xultmpl.xpt
