.TH SMJS 1 "7 March 2003"
.SH NAME
smjs - javascript shell
.SH SYNOPSIS
\fBsmjs\fP
.SH DESCRIPTION
The "JS shell", a simple interpreter program that uses the JS API and more
than a few internal interfaces (some of these internal interfaces could
be replaced by jsapi.h calls). The js program built from this
source provides a test vehicle for evaluating scripts and calling functions,
trying out new debugger primitives, etc.
.SH AUTHOR
This manpage was originally written by Bastian Kleineidam
<calvin@debian.org> for the Debian distribution of Spidermonkey.

The main author of Spidermonkey is the Mozilla Project.
