etc/gre.d/xulrunner.conf

usr/bin/xulrunner
usr/lib/xulrunner/xpt_dump
usr/lib/xulrunner/run-mozilla.sh
usr/lib/xulrunner/xpt_link
usr/lib/xulrunner/xpidl
usr/lib/xulrunner/regxpcom
usr/lib/xulrunner/xpcshell
usr/lib/xulrunner/mozilla-xremote-client
usr/lib/xulrunner/updater
usr/lib/xulrunner/xpicleanup
usr/lib/xulrunner/xulrunner-bin
usr/lib/xulrunner/xulrunner-stub

usr/lib/xulrunner/plugins

usr/lib/xulrunner/icons usr/share/xulrunner
usr/lib/xulrunner/chrome/icons usr/share/xulrunner/chrome

usr/lib/xulrunner/components/jsconsole-clhandler.js
usr/lib/xulrunner/components/nsCloseAllWindows.js
usr/lib/xulrunner/components/nsExtensionManager.js
usr/lib/xulrunner/components/nsKillAll.js
usr/lib/xulrunner/components/nsUpdateService.js
usr/lib/xulrunner/components/nsXULAppInstall.js
