/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is mozilla.org code.
 *
 * The Initial Developer of the Original Code is
 * Mike Hommey <mh@glandium.org>.
 * Portions created by the Initial Developer are Copyright (C) 2010
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either of the GNU General Public License Version 2 or later (the "GPL"),
 * or the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

#include "nsISupports.idl"
#include "nsIFile.idl"

typedef long debGIOFileMonitorEvent;
%{ C++
enum {
  DEB_GIO_FILE_MONITOR_EVENT_CHANGED = 0,
  DEB_GIO_FILE_MONITOR_EVENT_CHANGES_DONE_HINT,
  DEB_GIO_FILE_MONITOR_EVENT_DELETED,
  DEB_GIO_FILE_MONITOR_EVENT_CREATED,
  DEB_GIO_FILE_MONITOR_EVENT_ATTRIBUTE_CHANGED
};
%}

[scriptable, uuid(caf63993-5b22-4d0b-a4f5-97a7dfd28e8b)]
interface debIGIOFileMonitorObserver: nsISupports
{
  void notify(in nsIFile file, in debGIOFileMonitorEvent event_type);
};

[scriptable, uuid(c7cc29a4-a2c7-4f4c-9175-fa1f22201625)]
interface debIGIOFileMonitorService: nsISupports
{
  void monitor(in nsIFile file, in debIGIOFileMonitorObserver observer);
};

%{C++
#define DEB_GIOFILEMONITORSERVICE_CONTRACTID "@debian.org/gio-file-monitor-service;1"
%}
